### ISSUE TITLE
Obtaining the Edge matrix

### ISSUE THREAD

**Issue by ml14je** [nschloe/meshplex#105]
Hi there! Looking through your code, and can't seem to find how one would obtain the Edge matrix, much like Matlab's `initmesh`. Could you help out?

**Comment by nschloe** [comment]
I don't know initmesh. Please explain.

**Comment by ml14je** [comment]
In the Edge matrix e, the first and second rows contain indices of the starting and ending point, the third and fourth rows contain the starting and ending parameter values, the fifth row contains the edge segment number, and the sixth and seventh row contain the left- and right-hand side subdomain numbers.

I suppose I could write it myself, but thought it could perhaps be something of use. It is handy when looking at implementing boundary conditions.

**Comment by nschloe** [comment]
I don't know what "starting and ending parameter values", "edge segment number" and "left- and right-hand side subdomain numbers" mean.

**Comment by ml14je** [comment]
I think I can get everything that I need from `mesh.edges`, thank you!
