### ISSUE TITLE
mesh.boundary_edges missing

### ISSUE THREAD

**Issue by griff10000** [nschloe/meshplex#127]
Just upgraded `meshplex` and noticed that the code:

`mesh = meshplex.MeshTri(pts, cells)`
`bei = mesh.boundary_edges` 

throws the following error:

`AttributeError: 'MeshTri' object has no attribute 'boundary_edges'`

I have been using the data `bei` to identify boundary nodes.

Has this facility been replaced by something else?

**Comment by griff10000** [comment]
It looks like the `edges` has now been changed to `facets`. So, 
`bei = mesh.boundary_edges`
becomes
`bei = mesh.boundary_facets`

**Comment by nschloe** [comment]
I didn't mean to break backwards compatibility. I'll add mesh.boundary_edges in the next release.
