### ISSUE TITLE
configure repo to include LFS files (test meshes) in source tarballs

### ISSUE THREAD

**Issue by drew-parsons** [nschloe/meshplex#165]
github and LFS is sometimes tricky to get operating smoothly.  One of the problems is that when you pull a tarball from the github repo, the tarball contains the LFS reference files instead of the actual files that are being referenced.

The problem was raised at https://github.com/git-lfs/git-lfs/issues/1322 . Apparently it's related to the way `git archive` works.
Reportedly it has now been addressed, and there is a github repo configuration setting “Include Git LFS objects in archives” which enables LFS files to be included in source tarballs, see https://github.com/git-lfs/git-lfs/issues/1322#issuecomment-786199434

If github has indeed been fixed in the way reported there, could you consider activating the “Include Git LFS objects in archives” setting?

**Comment by nschloe** [comment]
Done! Thanks for letting me know.

**Comment by drew-parsons** [comment]
Confirmed. `gbp import-orig` now pulls a tarball with the mesh files rather than the lfs reference files.
