### ISSUE TITLE
[BUG] Cannot import name 'NDArray'

### ISSUE THREAD

**Issue by oldninja** [nschloe/meshplex#169]
**Describe the bug**
Exception error during import. Pygmsh and meshio worked fine without any issues.

```
Exception has occurred: ImportError
cannot import name 'NDArray' from 'numpy.typing' (/home/user/.local/lib/python3.9/site-packages/numpy/typing/__init__.py)
  File "/home/user/testing_meshes.py", line 3, in <module>
    import meshplex
```
**To Reproduce**
```
import math
import pygmsh
import meshplex
```

**Diagnose**
I may ask you to cut and paste the output of the following command.
```
pip freeze | grep meshplex
meshplex==0.16.7
```

**Did I help?**

If I was able to resolve your problem, consider [sponsoring](https://github.com/sponsors/nschloe) my work on meshplex, or [buy me a coffee](https://ko-fi.com/nschloe) to say thanks.

**Comment by nschloe** [comment]
Looks like you have an old numpy version installed.

**Comment by oldninja** [comment]
Updated and now it is working. Thank you @nschloe !
