### ISSUE TITLE
well-centeredness and delaunayhood

### ISSUE THREAD

**Issue by krober10nd** [nschloe/meshplex#64]
Hello, 

I'm just a curious reader. I noticed that you flip edges until all co-edge volumes are > 0 and you state that this achieve Delaunay-hood. However, I thought that all Delanay triangulations do not need to be well-centered (i.e., circum center inside the triangulation)? Isn't this a more strict requirement? 

Thanks for the awesome software,

**Comment by nschloe** [comment]
> circum center inside the triangulation

Are you talking about the boundary of the domain here? You're right. The flipping only refers to the interior. If you have a negative co-edge volume at a boundary edge, there's nothing you can flip anyway.

**Comment by krober10nd** [comment]
Yea, that's true.  I was just reading a little bit about it here 

https://arxiv.org/pdf/0802.2108.pdf

At one point I tried to do a edge flipper in fortran, I gave up when the edges kept criss-crossing. :]

**Comment by nschloe** [comment]
For reference, the flipping code is [here](https://github.com/nschloe/meshplex/blob/master/meshplex/mesh_tri.py#L1058). It was a bit of a hassle to get right, but I'm fairly happy with it now. If you're interested in mesh optimization, you might also want to check out https://github.com/nschloe/optimesh. From looking at the images in the article, optimesh seems a fair bit better at improving meshes.

**Comment by krober10nd** [comment]
Yes, I am using optmimesh already actually. It works great!

I've built a python mesh generator with some modifications to your dmesh package also for sesimological modeling. I'm currently trying to make it mpi parallel actually. I will submit a PR when it's done. 

I spent a good chunk of my PhD using a modified form of the distmesh algorithm in this package https://github.com/CHLNDDEV/OceanMesh2D so I know some tricks to make it more robust and faster.   However, my academic matlab days are in the rearview mirror now so only python now. 

Thanks!

**Comment by nschloe** [comment]
> However, my academic matlab days are in the rearview mirror now so only python now.

Good on you!

I'm also looking at dmsh right now, I believe it'll get better when replacing distmesh's "force edge" approach with something more sensible by optimesh. We'll see.

Feel free to close this issue if you consider it solved.
