### ISSUE TITLE
test error on i386 in test_flip_two_edges

### ISSUE THREAD

**Issue by drew-parsons** [nschloe/meshplex#78]
Hi Nico, does this error in `test_flip_two_edges` on i386 indicate there's a bug that needs to be fixed? If not, what's the best way to handle it??
```
_____________________________ test_flip_two_edges ______________________________

    def test_flip_two_edges():
        alpha = numpy.array([1.0, 3.0, 5.0, 7.0, 9.0, 11.0]) / 6.0 * numpy.pi
        R = [0.9, 1.0, 0.9, 1.0, 1.2, 1.0]
        points = numpy.array(
            [[r * numpy.cos(a), r * numpy.sin(a), 0.0] for a, r in zip(alpha, R)]
        )
        cells = numpy.array([[1, 3, 5], [0, 1, 5], [1, 2, 3], [3, 4, 5]])
        mesh = meshplex.MeshTri(points, cells)
        assert mesh.num_delaunay_violations() == 2
    https://ci.debian.net/data/autopkgtest/unstable/i386/p/python-meshplex/7605218/log.gz
        mesh.flip_until_delaunay()
        assert mesh.num_delaunay_violations() == 0
    
>       assert numpy.array_equal(
            mesh.cells["nodes"], [[5, 2, 3], [0, 2, 1], [5, 2, 0], [3, 4, 5]]
        )
E       assert False
E        +  where False = <function array_equal at 0xf6794778>(array([[2, 0, 1],\n       [2, 0, 5],\n       [5, 2, 3],\n       [3, 4, 5]]), [[5, 2, 3], [0, 2, 1], [5, 2, 0], [3, 4, 5]])
E        +    where <function array_equal at 0xf6794778> = numpy.array_equal

test/mesh_tri_test.py:613: AssertionError
```

Full test logs at
https://ci.debian.net/packages/p/python-meshplex/unstable/i386/
https://ci.debian.net/packages/p/python-meshplex/testing/i386/
https://ci.debian.net/data/autopkgtest/unstable/i386/p/python-meshplex/7605218/log.gz

**Comment by nschloe** [comment]
Yeah, this looks like a bug, though not sure if a meshplex bug. My debian dev application is still ongoing, so hopefully I'll have access to an i386 soon for reproducing the bug.

**Comment by mwhudson** [comment]
This test is failing on other architectures too in Ubuntu: ppc64el, arm64 and s390x, in fact all arches apart from amd64 and armhf.

I'm way too rusty on this sort of thing to tell if the result of the calculation on these architectures is incorrect, or simply a different but still valid triangulation. One thing that my spider sense tells me is that ppc64el, arm64 and s390x all have fused multiply add instructions and amd64 and armhf do not (or, well, amd64 mostly does not and they are not used with the default compilation options in Ubuntu) so if there is sensitivity to fine details of rounding that might explain the difference...

**Comment by mwhudson** [comment]
I've found the point of divergence on amd64 vs ppc64el and indeed it seems to be "sensitive to fine details of rounding". If you add "print(ce_ratios_per_interior_edge[edge_ids][1] - ce_ratios_per_interior_edge[edge_ids][2])" to code in flip_until_delaunay like so:

```python
                for cell_gid in critical_cell_gids:
                    edge_gids = self.cells["edges"][cell_gid]
                    num_adj_cells, edge_id = self._edge_gid_to_edge_list[edge_gids].T
                    edge_ids = edge_id[num_adj_cells == 2]
                    print(ce_ratios_per_interior_edge[edge_ids][1] - ce_ratios_per_interior_edge[edge_ids][2])
                    k = numpy.argmin(ce_ratios_per_interior_edge[edge_ids])
                    is_flip_interior_edge[edge_ids] = False
                    is_flip_interior_edge[edge_ids[k]] = True
```

on the amd64 it prints -1.6653345369377348e-16 so k ends up being 1 and on ppc64el it prints 5.551115123125783e-17 and so k ends up being 2, and so the algorithm goes down a different path. Still don't know if the algorithm is right or wrong but leaning more towards this being a valid but different response. Is it possible to tweak the test towards being more stable? Also suspecting we should just skip this test, or at least this assertion, in Ubuntu for now.

**Comment by nschloe** [comment]
Thanks @mwhudson for digging this up! I'll see if I can come up with a simple solution.

**Comment by nschloe** [comment]
Can you check if changing
```python
R = [0.9, 1.0, 0.9, 1.0, 1.2, 1.0]
```
to
```python
R = [0.8, 1.0, 0.9, 1.0, 1.2, 1.0]
```
fixes the tests? (This introduces a slight asymmetry to the mesh, hopefully nudging the flips into one particular direction.)

**Comment by nschloe** [comment]
Never mind, you need some more small changes. I'll prepare a PR.
